application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 60 * 60 * 60 * 1000
      rememberMeTokenValiditySeconds: 59 * 60 * 60 * 1000


mailServer:
  host: smtp.gmail.com
  port: 587
  email: phuvmph18216@fpt.edu.vn
  password: phuvmph18216
  protocol: smtp
  isSSL: false