
CREATE OR REPLACE FUNCTION updateStockAfterUpdateOrderDetailQuantity()
	RETURNS TRIGGER AS
$$
BEGIN
	UPDATE PRODUCT_DETAILS PRO
	SET STOCK = PRO.STOCK + ABS(OLD.QUANTITY) - ABS(NEW.QUANTITY)
	WHERE PRO.ID = NEW.PRODUCT_DETAIL_ID AND NEW.STATUS_ORDER_DETAIL IN (1,5);
	RETURN NEW;
END;
$$
	LANGUAGE 'plpgsql';
CREATE TRIGGER UPDATE_STOCK_AFTER_UPDATE_ORDER_DETAIL_QUANTITY
	AFTER UPDATE OF QUANTITY
	ON ORDER_DETAILS
	FOR EACH ROW
EXECUTE FUNCTION updateStockAfterUpdateOrderDetailQuantity()